### ISSUE TITLE
too many static variables

### ISSUE THREAD

**Issue by silent-mobius** [BigRush/install#3]
it is good practice to have a global variable that can be changed easy in a script at once.
for example:
 instead of checking them on by one  like this -->
cat /etc/*-release |grep ID |cut -d "=" -f "2" |egrep "^manjaro$" &> /dev/null
i would create variable tmp and have changed the target that i am seeking :
tmp=$(cat /etc/*-release |egrep '^ID' |awk -F = '{print $2}')
then i would have checked it against the cases of all OS's behaved accordingly
good luck

**Comment by BigRush** [comment]
fixed that and changed the entire distro validation function
